### ISSUE TITLE
qq红包日历

### ISSUE THREAD

**Issue by daimajia** [hotoo/hongbao#2]
:smile: qq也要发红包了！求加入日历～

**Comment by hotoo** [comment]
你看到的 QQ 红包信息在哪里？我找到这几个：
- http://tech.qq.com/a/20150209/064182.htm
- http://tech.qq.com/a/20150209/057653.htm
- http://www.cnbeta.com/articles/369387.htm
- http://news.mydrivers.com/1/385/385566.htm

**Comment by daimajia** [comment]
@hotoo http://www.cnbeta.com/articles/369387.htm 介个！ 你打开手机QQ也能看到。
